### ISSUE TITLE
ReferenceError: window is not defined when using with Nuxt

### ISSUE THREAD

**Issue by Hyperblaster** [CarterLi/vue3-ace-editor#26]
Hoping to use this with a Vue3 app running on Nuxt 3.
But i can't find a way to use this as it references `window` as soon as it's imported.

```
ReferenceError: window is not defined
    at /nuxt3-app/node_modules/ace-builds/src-noconflict/ace.js:21534:21
    at _require (/nuxt3-app/node_modules/ace-builds/src-noconflict/ace.js:88:37)
```

Do you know if there is a way that we can wrap this or include it only after the `mounted` lifecycle hook?

**Comment by CarterLi** [comment]
Maybe use dynamic import？

**Comment by rahulkumarsingh73690** [comment]
@Hyperblaster Any solution?

**Comment by CarterLi** [comment]
Does this work?

```
const VAceEditor = defineDynamicComponent(() => import('vue3-ace-editor').then(x => VAceEditor)
```

**Comment by rahulkumarsingh73690** [comment]
Not working @CarterLi 

![image](https://user-images.githubusercontent.com/37482171/188673056-7b622c2a-bc84-4ac2-897c-9b9639492d8c.png)

**Comment by CarterLi** [comment]
Should be [defineAsyncComponent](https://vuejs.org/api/general.html#defineasynccomponent)

**Comment by rahulkumarsingh73690** [comment]
The error is gone but still not working. I can't render ace editor

**Comment by CarterLi** [comment]
const VAceEditor = defineAsyncComponent(() => import('vue3-ace-editor').then(x => x.VAceEditor)

**Comment by rahulkumarsingh73690** [comment]
Still not working. If you are using discord then please help me

![image](https://user-images.githubusercontent.com/37482171/188679442-12c7250f-1b35-44c5-b990-2c9ac414e681.png)

**Comment by CarterLi** [comment]
Okey, found a dirty hack

```ts
// ace-editor.ts

import 'ace-builds/src-noconflict/ace';
import 'ace-builds/src-noconflict/mode-json';
import 'ace-builds/src-noconflict/theme-chrome';
import { VAceEditor } from 'vue3-ace-editor';

export default VAceEditor;
```

```vue
<script lang="ts" setup>
// app.vue

import { defineAsyncComponent, h } from 'vue'
const VAceEditor = defineAsyncComponent(() => {
  if (typeof window !== 'undefined') {
    return import('./ace-editor');
  } else {
    return Promise.resolve(defineComponent({
      inheritAttrs: false,
      props: { value: String },
      render() { return h('div', { style: 'font-family: monospace; white-space: pre-wrap' }, this.value) },
    }) as unknown as typeof import('./ace-editor'));
  }
});
</script>
<template>
  <VAceEditor lang="json" value="{ hello: 'world' }" readonly style="height: 300px" />
</template>
```

**Comment by rahulkumarsingh73690** [comment]
Thanks for sharing this method but i don't think this is suitable for my website. I have multiple pages and all pages includes different ace language and theme. So if i import all in one script then my website became too heavy.

**Comment by CarterLi** [comment]
https://github.com/CarterLi/vue3-ace-editor#breaking-change

Dynamic modes loading should work here

**Comment by rahulkumarsingh73690** [comment]
Are you sure this method work in nuxt 3?

**Comment by CarterLi** [comment]
Check the code here: https://github.com/CarterLi/nuxt-ace

**Comment by rahulkumarsingh73690** [comment]
Thanks this works but as I told you earlier I want java languages in one pages and Php language in another page. So if I import all in one ace-editor.ts

Page size became too large. Is there any way to import inside page without creating ace-editor.ts.

Thanks buddy for your help I really appreciate 😍

**Comment by CarterLi** [comment]
Read this

> https://github.com/CarterLi/vue3-ace-editor#breaking-change
> 
> Dynamic modes loading should work here

**Comment by rahulkumarsingh73690** [comment]
> Read this
> 
> > https://github.com/CarterLi/vue3-ace-editor#breaking-change
> > Dynamic modes loading should work here

Can you please show me a demo? If possible because i tried this and did not worked for me

**Comment by CarterLi** [comment]
https://github.com/CarterLi/nuxt-ace/blob/master/ace-editor.ts#L3

**Comment by rahulkumarsingh73690** [comment]
Do you mean this?

https://goonlinetools.com/snapshot/code/#syp4a715fpfgpvci69tm8

**Comment by CarterLi** [comment]
I don't think you have the basic knowledge of using ES module. Learn it first.
