### ISSUE TITLE
Allow more than one editor instance, when using syntax checking.

### ISSUE THREAD

**Issue by tmikaeld** [CarterLi/vue3-ace-editor#30]
If there is more than 1 editor, then syntax checking fails for all of them. 

Console shows this error:
```
vue-router.mjs:3441 TypeError: Cannot read properties of undefined (reading 'setOptions')
    at Proxy.options (index.ts:111:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at job (runtime-core.esm-bundler.js:1776:17)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:318:13)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5742:9)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5655:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5716:56)
    at updateComponent (runtime-core.esm-bundler.js:5541:26)
```

Seems to be an issue with how `:options="{ useWorker: false }"` is handled to set `setOptions` for ace.

**Comment by CarterLi** [comment]
Minimal repo please?

**Comment by tmikaeld** [comment]
It was an issue with Quasars Dialog plugin in combination with Vue3 Ace, seems to be a memory leak as well, I'll report it to the correct maintainer. Sorry for wasting you time on this!

**Comment by tmikaeld** [comment]
@CarterLi I had to switch to init the worker via the @init action and there set the worker via:
```
function initEditor(editor) {
 editor.setOptions({ useWorker: true });
}
```
Otherwise it would collide with Quasar components and spiral into loops and bad state, causing memory load and hangs.
